# Dependencies

source:         "."
url:            "https://italia.github.io/design-comuni-prototipi"
baseurl:        "/design-comuni-prototipi"
destination:    ./_site
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - AUTHORS
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.sketch"

# CDN links
cdn:
  bootstrap_italia_js_bundle: 'https://cdn.jsdelivr.net/npm/bootstrap-italia@0.27.3/dist/js/bootstrap-italia.bundle.min.js'
  bootstrap_italia_css:       'https://cdn.jsdelivr.net/npm/bootstrap-italia@0.27.3/dist/css/bootstrap-italia.min.css'
