# Dependencies

source:         "."
url:            "https://italia.github.io/design-comuni-prototipi"
baseurl:        "/design-comuni-prototipi"
destination:    ./_site
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - AUTHORS
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - README.md
  - "*.sketch"

# CDN links
cdn:
  bootstrap_italia_js_bundle: 'static/js/bootstrap-italia.bundle_1.2.0.min.js'
  bootstrap_italia_css:       'static/css/bootstrap-italia_1.2.0.min.css'
